FROM itsafeaturemythic/csharp_payload:0.0.15
RUN python3.8 -m pip uninstall -y mythic_payloadtype_container
RUN python3.8 -m pip install --index-url https://test.pypi.org/simple/ mythic_payloadtype_container==0.0.91